site_name: policy-machine-core
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Functional Components: functional-components.md
  - Obligations: obligations.md
  - Examples: examples.md
  - Contact Us: contact.md
theme:
  name: 'material'
extra_css:
  - css/extra.css
